name: Hexo Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy blog.
    steps:
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
    - uses: yrpang/github-actions-hexo@v1.3
      with:
        deploykey: ${{secrets.DEPLOY_KEY}}
        username: PttCodingMan
        email: pttcodingman@gmail.com
    - name: Push Resume to Github Page
      working-directory: public
      run: |
        git config --global user.name "${{ secrets.DEVOPS_NAME }}"
        git config --global user.email "${{ secrets.DEVOPS_EMAIL }}"
        
        git init .
        git add -A
        git commit -m "Updated blog."
        git -f push
